export const MEETINGS_RECEIVED = 'MEETINGS_RECEIVED';
export const MEETINGS_FETCH_FAILED = 'MEETINGS_FETCH_FAILED';
export const START_MEETINGS_REQUEST = 'START_MEETINGS_REQUEST';

export const CLIENT_SET = 'CLIENT_SET';
export const LOGIN_REQUEST = 'LOGIN_REQUEST';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';

export const RESET_MEETINGS = 'RESET_MEETINGS';
export const CREATE_MEETING_REQUEST = 'CREATE_MEETING_REQUEST';
export const CREATE_MEETING_CANCEL = 'CREATE_MEETING_CANCEL';
export const CREATE_MEETING_START = 'CREATE_MEETING_START';
export const CREATE_MEETING_SUCCESS = 'CREATE_MEETING_SUCCESS';
export const CREATE_MEETING_FAILURE = 'CREATE_MEETING_FAILURE';

export const CLOSE_MEETING_DIALOG = 'CLOSE_MEETING_DIALOG';
