export const MEETINGS_FETCH_START = 'MEETINGS_FETCH_START';
export const MEETINGS_FETCH_SUCCEEDED = 'MEETINGS_FETCH_SUCCEEDED';
export const MEETINGS_FETCH_FAILED = 'MEETINGS_FETCH_FAILED';

export const MEETING_CREATE_START = 'MEETING_CREATE_START';
export const MEETING_CREATE_SUCCEEDED = 'MEETING_CREATE_SUCCEEDED';
export const MEETING_CREATE_FAILED = 'MEETING_CREATE_FAILED';

export const LOGIN_START = 'LOGIN_START';
export const LOGIN_SUCCEEDED = 'LOGIN_SUCCEEDED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGOUT = 'LOGOUT';

export const RESET_MEETINGS = 'RESET_MEETINGS';
export const POPULATE_MEETING_FORM = 'POPULATE_MEETING_FORM';
export const CREATE_MEETING_CANCEL = 'CREATE_MEETING_CANCEL';
export const CLOSE_MEETING_DIALOG = 'CLOSE_MEETING_DIALOG';
export const SET_USER = 'SET_USER';
export const RESET_USER = 'RESET_USER';
