export const SET_AUTHENTICATION = 'SET_AUTHENTICATION'
export const SET_AUTHORIZATION = 'SET_AUTHORIZATION'
export const CLEAR_AUTH = 'CLEAR_AUTH'

export const SET_USER = 'SET_USER'
export const CLEAR_USER = 'CLEAR_USER'

export const LOGIN_REQUEST = 'LOGIN_REQUEST'
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS'
// export const LOGIN_ERROR = 'LOGIN_ERROR'

export const LOGOUT_REQUEST = 'LOGOUT_REQUEST'
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS'

export const SELECT_DATE = 'SELECT_DATE'
export const INCREMENT_DATE = 'INCREMENT_DATE'
export const DECREMENT_DATE = 'DECREMENT_DATE'

export const FETCH_ROOMS = 'FETCH_ROOMS'
export const RECEIVE_ROOMS = 'RECEIVE_ROOMS'

export const FETCH_MEETINGS = 'FETCH_MEETINGS'
export const RECEIVE_MEETINGS = 'RECEIVE_MEETINGS'

// DUBIOUS BULLSHIT BELOW

export const AUTHORIZE_REQUEST = 'AUTHORIZE_REQUEST'
export const AUTHORIZE_SUCCESS = 'AUTHORIZE_SUCCESS'
export const AUTHORIZE_ERROR = 'AUTHORIZE_ERROR'

